"""sort relations

Revision ID: 1f55e6f5726b
Revises: 
Create Date: 2019-10-27 12:14:47.887204

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f55e6f5726b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('messages',
    sa.Column('mid', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.Time(), nullable=True),
    sa.Column('text', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('mid')
    )
    op.create_table('users',
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=128), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('userschats',
    sa.Column('ucid', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.Time(), nullable=True),
    sa.Column('chats_cid', sa.Integer(), nullable=True),
    sa.Column('users_uid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['chats_cid'], ['messages.mid'], ),
    sa.ForeignKeyConstraint(['users_uid'], ['users.uid'], ),
    sa.PrimaryKeyConstraint('ucid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('userschats')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('messages')
    # ### end Alembic commands ###
