"""initial

Revision ID: c91dd34c5ca2
Revises: 
Create Date: 2019-10-28 14:43:58.620134

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c91dd34c5ca2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chats',
    sa.Column('cid', sa.Integer(), nullable=False),
    sa.Column('chatname', sa.String(length=256), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('cid')
    )
    op.create_index(op.f('ix_chats_timestamp'), 'chats', ['timestamp'], unique=False)
    op.create_table('users',
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('timestamp', sa.Time(), nullable=True),
    sa.Column('email', sa.String(length=128), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_timestamp'), 'users', ['timestamp'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('messages',
    sa.Column('mid', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('text', sa.String(length=256), nullable=True),
    sa.Column('userfrom', sa.Integer(), nullable=True),
    sa.Column('cid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cid'], ['chats.cid'], ),
    sa.ForeignKeyConstraint(['userfrom'], ['users.uid'], ),
    sa.PrimaryKeyConstraint('mid')
    )
    op.create_index(op.f('ix_messages_timestamp'), 'messages', ['timestamp'], unique=False)
    op.create_table('userschat',
    sa.Column('ucid', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.Time(), nullable=True),
    sa.Column('users_uid', sa.Integer(), nullable=True),
    sa.Column('chats_cid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['chats_cid'], ['chats.cid'], ),
    sa.ForeignKeyConstraint(['users_uid'], ['users.uid'], ),
    sa.PrimaryKeyConstraint('ucid')
    )
    op.create_index(op.f('ix_userschat_timestamp'), 'userschat', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_userschat_timestamp'), table_name='userschat')
    op.drop_table('userschat')
    op.drop_index(op.f('ix_messages_timestamp'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_timestamp'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_chats_timestamp'), table_name='chats')
    op.drop_table('chats')
    # ### end Alembic commands ###
